config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  
  # jobs_controller系
  get "jobs/copied_new" => "jobs#copied_new"
  post "jobs/copied_create" => "jobs#copied_create"
  # 【こっちに統合】進捗ごとに一覧を表示
  get "jobs/index" => "jobs#index_progress"
  get "jobs/ordered_index" => "jobs#ordered_index"
  resources :jobs do 
    # レビュー絡み
    resources :reviews
  end
  # ヘルパーがエントリー
  get "jobs/entry/:id" => "jobs#entry"
  # エントリー完了
  get "jobs/entry_complete/:id" => "jobs#entry_complete"
  # エントリー取り下げ
  get "jobs/entry_cancel/:id" => "jobs#entry_cancel"
  # 労働条件提示書承認入力
  get "jobs/condition_confirm/:id" => "jobs#condition_confirm"
  # 労働条件提示書確認完了
  get "jobs/condition_complete/:id" => "jobs#condition_complete"
  # 事業所がエントリーを承認
  get "jobs/entry_confirm/:id" => "jobs#entry_confirm"
  # エントリー承認後
  get "jobs/entry_confirm_complete/:id" => "jobs#entry_confirm_complete"
  # エントリーを却下
  get "jobs/entry_rejection/:id" => "jobs#entry_rejection"
  # 仕事完了を確認
  get "jobs/job_close/:id" => "jobs#job_close"
  # 完了入力後
  get "jobs/job_close_complete/:id" => "jobs#job_close_complete"

  # チャットルーム
  resources :rooms
  # 仕事のカテゴリー
  resources :job_categories, only: [:new, :create]

  # ヘルパー絡み
  devise_for :heros, controllers: {
    sessions:      'heros/sessions',
    passwords:     'heros/passwords',
    registrations: 'heros/registrations',
    confirmations: 'heros/confirmations'
  }
  devise_scope :hero do
    get "heros/confirmation" => "heros/registrations#confirmation"
  end
  
  # 登録完了の画面
  get "heros/success"
  # メール認証を依頼する画面
  get "heros/checkmail"
  # 利用規約の確認
  get "heros/rules" => "heros#rules"
  # ヘルパーのプロフィールを表示
  get "heros/profile/:id" => "heros#profile"
  # ヘルパーのマイページを表示
  resources :heros, only: [:show]
  
  # 管理者絡み
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  # 介護事業所絡み
  devise_for :nursing_homes, controllers: {
    sessions:      'nursing_homes/sessions',
    passwords:     'nursing_homes/passwords',
    registrations: 'nursing_homes/registrations',
    confirmations: 'nursing_homes/confirmations'
  }
  # 登録完了の画面
  get "nursing_homes/success"
  # メール認証を依頼する画面
  get "nursing_homes/checkmail"
  get "nursing_homes/profile/:id" => "nursing_homes#profile"
  resources :nursing_homes, only: [:show]

end

app/models/nursing_home.rb
class NursingHome < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  # アソシエーション
  has_many :jobs
  # belongs_to :type
  has_many :reviews
  has_many :nursing_home_messages
end

app/controllers/nursing_homes/confirmations_controller.rb
# frozen_string_literal: true

class NursingHomes::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    nursing_homes_success_path
  end
end

app/controllers/nursing_homes/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class NursingHomes::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/nursing_homes/passwords_controller.rb
# frozen_string_literal: true

class NursingHomes::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/nursing_homes/registrations_controller.rb
# frozen_string_literal: true

class NursingHomes::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :contact_person, :phone, :detail])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :contact_person, :phone, :website, :detail])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    nursing_homes_success_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    nursing_homes_checkmail_path
  end
  
  def after_update_path_for(resource)
    nursing_home_path(resource)
  end
end

app/controllers/nursing_homes/sessions_controller.rb
# frozen_string_literal: true

class NursingHomes::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
  
  # サインイン後に飛ぶページを指定
  def after_sign_in_path_for(resource)
    nursing_home_path(resource)
  end
end

app/controllers/nursing_homes/unlocks_controller.rb
# frozen_string_literal: true

class NursingHomes::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/nursing_homes_controller.rb
class NursingHomesController < ApplicationController
before_action :authenticate_nursing_home!, only: [:show]

  def show
   @nursing_home = NursingHome.includes(:jobs).find(params[:id])
  end
  
  def profile
    @nursing_home = NursingHome.includes(:jobs).find(params[:id])
  end
  
end

app/helpers/nursing_homes_helper.rb
module NursingHomesHelper
end

app/views/nursing_homes/checkmail.html.erb
<%= render partial: 'layouts/top_header' %>

<main class="style-main style-ma-tlow mb-5">
  <section class="container-fluid">
    <div class="row">
      <div class="col-lg-3">
      </div>
      <div class="col-lg-6">
        <div class="mb-5">
          <h1 class="style-centertext mb-3">入力されたメールアドレスに認証メールが送信されました</h1>
          <p class="style-centertext">メール内のリンクをクリックして、登録を完了させてください</p>
        </div>
        <div>
          <div class="row">
            <div class="col-lg-6">
              <div class="style-centertext mb-3">
                <%= link_to root_path do %>
                  <button class="style-boder-smallradius style-orderreq-entrybtn">トップへ戻る</button>
                <% end %>
              </div>
            </div>
          </div>
          <div class="mt-5">
            <figure class="style-centertext">
              <img src="/assets/character/Rabbit-Phone-Coment.jpg" alt="認証メール送信完了画像" width="80%" height="80%">
            </figure>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </section>
</main>

app/views/nursing_homes/profile.html.erb
  <h3><%= @nursing_home.name %>様 登録情報</h3>
  <br />
  <br />
  <p>-----------------------------------------------------------------------------------</p>
  <p>メールアドレス：<%= @nursing_home.email %></p>
  <p>住所：
    <% if @nursing_home.address? %>
      <%= @nursing_home.address %>
    <% else %>
      <span>未設定</span>
    <% end %>
  </p>
  <p>ウェブサイト:
    <% if @nursing_home.website? %>
      <%= link_to "#{@nursing_home.website}", "#{@nursing_home.website}", target: :_blank, rel: "noopener noreferrer" %>
    <% else %>
      <span>未設定</span>
    <% end %>
  </p>
  <p>連絡先（電話番号）：
    <% if @nursing_home.phone? %>
      <%= @nursing_home.phone %>
    <% else %>
      <span>未設定</span>
    <% end %>
  </p>
  <p>連絡担当者:
    <% if @nursing_home.contact_person? %>
      <%= @nursing_home.contact_person %>
    <% else %>
      <span>未設定</span>
    <% end %>
  </p>
  <p>-----------------------------------------------------------------------------------</p>
  
<br />
<br />
<br />
  
  <% if nursing_home_signed_in? %>
    <% if @nursing_home.id == current_nursing_home.id %>
    <p><%= link_to "登録情報を編集する", edit_nursing_home_registration_path(current_nursing_home.id) %></p>
    <p><%= link_to "管理画面へ戻る", nursing_home_path(current_nursing_home.id) %></p>
    <% end %>
  <% end %>
  <p><%= link_to "トップへ戻る", root_path %></p>

app/views/nursing_homes/show.html.erb
<%= render partial: 'layouts/header' %>

<main>
  <article class="top-container">
    <section class="top-title nursing_homes-top">
      <h1>ハロヒロにようこそ</h1>
      <div class="nursing_homes-top__contents">
        <p>
          ご利用ありがとうございます。あなたの職場にヒーローを要請してください。
        </p>
        <img
          src="/assets/character/Lion-Guts-Coment.jpg"
          alt="事業所さんトップページ画像"
        />
      </div>
    </section>
    <section class="nursing_homes-top--info">
      <h2 class="section-title">
        <span class="section-title__icon"
          ><i class="fas fa-home" aria-hidden="true"></i></span
        >事業所情報
      </h2>
      <div class="nursing_homes-top--info--major">
        <img
          src="/assets/character/Lion-Stand.jpg"
          alt="事業所画像"
        />
        <div class="nursing_homes-top--info--text">
          <h3>事業所名</h3>
          <p><%= @nursing_home.name %></p>
          <h3>事務所種別</h3>
          <p>訪問看護ステーション</p>
          <h3>担当者</h3>
          <p><%= @nursing_home.contact_person %></p>
        </div>
        <div class="nursing_homes-top--info--text">
          <h3>電話番号</h3>
          <p><%= @nursing_home.phone %></p>
          <h3>住所</h3>
          <p><%= @nursing_home.address %></p>
          <h3>アクセス情報</h3>
          <p>新宿駅より徒歩１５分 タバコ屋の近くにあります</p>
        </div>
      </div>
      <h3>事業所情報</h3>
      <p>
        <%= @nursing_home.detail %>
      </p>
      <h3>事業所番号（指定番号）</h3>
      <p>1234-567890-1</p>
    </section>
    <section>
      <h2 class="section-title">
        <span class="section-title__icon"
          ><i class="fas fa-user-plus" aria-hidden="true"></i></span
        >お仕事登録方法
      </h2>
      <div class="nursing_homes-top__work">
        <h3>やり方は、お仕事を登録してヘルパーさんの応募を待つだけ!</h3>
        <div class="nursing_homes-top__work--contents">
          <div class="nursing_homes-top__work--contents__box">
            <h4>○お仕事を登録</h4>
            <img
              src="/assets/character/Lion-Stand.jpg"
              alt="お仕事依頼画像"
            />
            <p>登録画面からお仕事を簡単に依頼できます</p>
          </div>
          <div class="nursing_homes-top__work--contents__box">
            <h4>○ヒーロー（ヘルパーさん）を待つ</h4>
            <img
              src="/assets/character/Rabbit-Phone.jpg"
              alt="ヘルパーさん応募"
            />
            <p>ヒーローへの積極的なアプローチもお任せ！</p>
          </div>
          <div class="nursing_homes-top__work--contents__box">
            <h4>○ヒーローと契約</h4>
            <img
              src="/assets/character/Lion-Guts.jpg"
              alt="契約完了画像"
            />
            <p>ヒーローがあなたのお仕事を助けてくれます</p>
          </div>
        </div>
      </div>
      <div class="nursing_homes-top__work--submit">
        <p>↓お仕事の依頼はこちらから↓</p>
        <%= link_to new_job_path do %>
          <button class="submit-btn">
            <i class="fas fa-pen"></i>
            <p>お仕事を登録する</p>
          </button>
        <% end %>
      </div>
    </section>
  </article>
</main>

app/views/nursing_homes/success.html.erb
<%= render partial: 'layouts/top_header' %>

<main class="style-main style-ma-tlow mb-5">
  <section class="container-fluid">
    <div class="row">
      <div class="col-lg-3">
      </div>
      <div class="col-lg-6">
        <div class="mb-5">
          <h1 class="style-centertext mb-3">会員登録が完了しました！</h1>
        </div>
        <div>
          <div class="row">
            <div class="col-lg-6">
              <div class="style-centertext mb-3">
                <%= link_to new_nursing_home_session_path do %>
                  <button class="style-boder-smallradius style-orderreq-entrybtn">ログイン</button>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
              <div class="style-centertext mb-3">
                <%= link_to root_path do %>
                  <button class="style-boder-smallradius style-orderreq-entrybtn">トップへ戻る</button>
                <% end %>
              </div>
            </div>
          <div class="mt-5">
            <figure class="style-centertext">
              <img src="/assets/character/Rabbit-Phone-Coment.jpg" alt="登録完了完了画像" width="80%" height="80%">
            </figure>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </section>
</main>