config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  
  # jobs_controller系
  get "jobs/copied_new" => "jobs#copied_new"
  post "jobs/copied_create" => "jobs#copied_create"
  # 【こっちに統合】進捗ごとに一覧を表示
  get "jobs/index" => "jobs#index_progress"
  get "jobs/ordered_index" => "jobs#ordered_index"
  resources :jobs do 
    # レビュー絡み
    resources :reviews
  end
  # ヘルパーがエントリー
  get "jobs/entry/:id" => "jobs#entry"
  # エントリー完了
  get "jobs/entry_complete/:id" => "jobs#entry_complete"
  # エントリー取り下げ
  get "jobs/entry_cancel/:id" => "jobs#entry_cancel"
  # 労働条件提示書承認入力
  get "jobs/condition_confirm/:id" => "jobs#condition_confirm"
  # 労働条件提示書確認完了
  get "jobs/condition_complete/:id" => "jobs#condition_complete"
  # 事業所がエントリーを承認
  get "jobs/entry_confirm/:id" => "jobs#entry_confirm"
  # エントリー承認後
  get "jobs/entry_confirm_complete/:id" => "jobs#entry_confirm_complete"
  # エントリーを却下
  get "jobs/entry_rejection/:id" => "jobs#entry_rejection"
  # 仕事完了を確認
  get "jobs/job_close/:id" => "jobs#job_close"
  # 完了入力後
  get "jobs/job_close_complete/:id" => "jobs#job_close_complete"

  # チャットルーム
  resources :rooms
  # 仕事のカテゴリー
  resources :job_categories, only: [:new, :create]

  # ヘルパー絡み
  devise_for :heros, controllers: {
    sessions:      'heros/sessions',
    passwords:     'heros/passwords',
    registrations: 'heros/registrations',
    confirmations: 'heros/confirmations'
  }
  devise_scope :hero do
    get "heros/confirmation" => "heros/registrations#confirmation"
  end
  
  # 登録完了の画面
  get "heros/success"
  # メール認証を依頼する画面
  get "heros/checkmail"
  # 利用規約の確認
  get "heros/rules" => "heros#rules"
  # ヘルパーのプロフィールを表示
  get "heros/profile/:id" => "heros#profile"
  # ヘルパーのマイページを表示
  resources :heros, only: [:show]
  
  # 管理者絡み
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  # 介護事業所絡み
  devise_for :nursing_homes, controllers: {
    sessions:      'nursing_homes/sessions',
    passwords:     'nursing_homes/passwords',
    registrations: 'nursing_homes/registrations',
    confirmations: 'nursing_homes/confirmations'
  }
  # 登録完了の画面
  get "nursing_homes/success"
  # メール認証を依頼する画面
  get "nursing_homes/checkmail"
  get "nursing_homes/profile/:id" => "nursing_homes#profile"
  resources :nursing_homes, only: [:show]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career_tag.rb
class CareerTag < ApplicationRecord
  # アソシエーション
  has_many :tag_maps
end

app/models/hero.rb
class Hero < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  # アソシエーション
  has_many :reviews
  has_many :tag_maps
  has_many :hero_messages
  has_many :rooms
  has_many :jobs
  
  # 画像アップローダ設定
  mount_uploader :image, ImageUploader
end

app/models/hero_message.rb
class HeroMessage < ApplicationRecord
  # アソシエーション
  belongs_to :hero
  belongs_to :room
end

app/models/job.rb
class Job < ApplicationRecord
  # アソシエーション
  belongs_to :job_category
  belongs_to :nursing_home
  belongs_to :hero
  has_one :review
  
  # アップロード
  mount_uploader :image, ImageUploader
  
  scope :search, -> (search_params) do
    # search_paramsが空の場合以降の処理を行わない。
    # >> [].blank?
    # => true
    return if search_params.blank?
    
    # パラメータを指定して検索を実行する
    title_like(search_params[:title])
      .job_category_id_is(search_params[:job_category_id])
      .date_is(search_params[:date])
      .time_from(search_params[:time_from])
      .time_to(search_params[:time_to])
  end
  
  # titleが存在する場合、titleをlike検索する
  scope :title_like, -> (title) { where('title LIKE ?', "%#{title}%") if title.present? }
  # job_category_idが存在する場合、job_category_idをlike検索する
  scope :job_category_id_is, -> (job_category_id) { where(job_category_id: job_category_id) if job_category_id.present? }
  # start_datetimeが存在する場合、start_datetimeで検索する
  scope :date_is, -> (date) { where( datetime: date) if date.present? }
  # timeが存在する場合、timeで範囲検索する
  scope :time_from, -> (from) { where( '? <= time', from) if from.present? }
  scope :time_to, -> (to) { where( 'time <= ?', to) if to.present? }
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
  has_many :jobs
end

app/models/message.rb
class Message < ApplicationRecord
  # アソシエーション
  belongs_to :hero
  belongs_to :room
  belongs_to :nursing_home
end

app/models/nursing_home.rb
class NursingHome < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  # アソシエーション
  has_many :jobs
  # belongs_to :type
  has_many :reviews
  has_many :nursing_home_messages
end

app/models/review.rb
class Review < ApplicationRecord
  # アソシエーション
  belongs_to :nursing_home
  belongs_to :job
  belongs_to :hero
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hero
  belongs_to :nursung_home
  has_many :hero_messages
  has_many :nursing_home_messages
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :hero
  belongs_to :career_tag
end

app/models/type.rb
class Type < ApplicationRecord
  # has_many :nursing_homes
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_form_logo.html.erb
<div class="style-nav style-smnav-line">
  <%= link_to root_path do %>
    <figure>
      <img src="/assets/Heros-Logo.png" alt="ハロヒロロゴ画像" height="40px" width="134px">
    </figure>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<!--トップページ以外の-->
<header class="wide-header">
  <div class="header--logo">
    <a href="#">
      <img src="/assets/Heros-Logo.png" alt="ヒーローズロゴ画像" />
    </a>
  </div>
  <nav>
    <ul class="header--nav nursing_homes--nav">
      <% if hero_signed_in? %>
        <li>
          <%= link_to jobs_path, class: "nav-item nav-link d-lg-inline-block style-text-black mr-lg-3" do%>
            <p><i class="fas fa-briefcase"></i>ミッション一覧</p>
          <% end %>
        </li>
        <li>
          <%= link_to hero_path(current_hero.id), class: "nav-item nav-link d-lg-inline-block style-text-black mr-lg-3" do%>
            <p><i class="fas fa-check"></i>やることリスト</p>
          <% end %>
        </li>
        <li>
          <%= link_to hero_path(current_hero.id), class: "nav-item nav-link d-lg-inline-block style-text-black mr-lg-3" do%>
            <p><i class="fas fa-bell"></i>お知らせ</p>
          <% end %>
        </li>
        <li>
          <%= link_to hero_path(current_hero.id), class: "nav-item nav-link d-lg-inline-block style-text-black" do%>
            <p><i class="fas fa-user"></i>マイページ</p>
          <% end %>
        </li>
      <% elsif nursing_home_signed_in? %>
        <li>
          <%= link_to new_job_path,class:"nav-item nav-link d-lg-inline-block style-text-black mr-lg-3"  do %>
            <p><i class="fas fa-users"></i>お仕事登録</p>
          <% end %>
        </li>
        <li>
          <%= link_to jobs_path, class: "nav-item nav-link d-lg-inline-block style-text-black" do%>
            <p><i class="fas fa-users"></i>お仕事一覧</p>
          <% end %>
        </li>
        <li>
          <%= link_to nursing_home_path(current_nursing_home.id), class: "nav-item nav-link d-lg-inline-block style-text-black" do%>
            <p><i class="fas fa-users"></i>管理画面</p>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_nursing_home_session_path, method: :delete, data: { confirm: "ログアウトしてよろしいですか？" }, id: "Destroy-btn-Show1", onclick: "LogoutFormHeros()" , class: "style-mypage-listitem" do %>
            ログアウト<i class="fas fa-chevron-right style-mypage-navicon"></i>
          <% end %>
        </li>
      <% end %>
  </nav>
</header>

app/views/layouts/_job_cards.html.erb
<% jobs.each do |job| %>
  <div class="workbox">
    <div class="workbox__container">
      <% if job.image? %>
        <div class="workbox__container__img">
          <%= image_tag job.image.url(:thumb), alt:"お仕事画像" %>
        </div>
      <% else%>
        <div class="workbox__container__img">
          <img src="assets/Heros-Logo.png" alt="お仕事画像（デフォルト）">
        </div>
      <% end %>
      <div class="workbox__contents">
        <span class="worktab--pink worktab__mini"><%= job.job_category.name %></span>
        <h3><%= link_to "#{job.title.truncate(10)}", job_path(job.id) %></h3>
        <p><%= job.service.truncate(20) %></p>
        <ul>
          <li><i class="fas fa-calendar-alt"></i><%= shape_job_date(job.start_datetime) %></li>
          <li><i class="fas fa-clock"></i><%= shape_job_start_time(job.start_datetime) %>~<%= shape_job_end_time(job.start_datetime + (job.time * 3600)) %></li>
          <li><i class="fas fa-map-marker-alt"></i><%= job.area %></li>
          <li><i class="fas fa-yen-sign"></i><%= job.price.to_s(:delimited) %></li>
        </ul>
        <% if hero_signed_in? %>
          <% if job.progress == 0 %>
            <div class="my-3">
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-entrybtn style-boder-smallradius ">挑戦する</button>
              <% end %>
            </div>
          <% elsif job.progress == 1 %>
            <div class="my-3">
              <% if job.hero_id == current_hero.id %>
                <%= link_to job_path(job.id) do %>
                  <button class="style-jobs-entrybtn style-boder-smallradius ">エントリー済</button>
                <% end %>
              <% else %>
                <button class="style-jobs-entrybtn style-boder-smallradius ">エントリー済</button>
              <% end %>
            </div>
          <% elsif job.progress == 2 && job.hero_id == current_hero.id %>
            <div class="my-3">
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-entrybtn style-boder-smallradius ">契約手続き中</button>
              <% end %>
            </div>
          <% elsif job.progress == 3 && job.hero_id == current_hero.id %>
            <div class="my-3">
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-entrybtn style-boder-smallradius ">契約中</button>
              <% end %>
            </div>
          <% elsif job.progress == 4 && job.hero_id == current_hero.id %>
            <div class="my-3">
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-entrybtn style-boder-smallradius ">評価が登録されました</button>
              <% end %>
            </div>
          <% elsif job.progress == 5 && job.hero_id == current_hero.id %>
            <div class="my-3">
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-entrybtn style-boder-smallradius ">完了済み</button>
              <% end %>
            </div>
          <% end %>
        <% elsif nursing_home_signed_in? && job.nursing_home_id == current_nursing_home.id %>
          <div>
            <%= link_to jobs_copied_new_path(job.id) do %>
              <button class="style-boder-smallradius my-3">コピーして新規登録</button>
            <% end %>
          </div>
          <div>
            <% if job.progress == 0 %>
              <%= link_to edit_job_path(job.id) do  %>
                <button class="style-jobs-editbtn style-boder-smallradius">編集する</button>
              <% end %>
              <%= button_to "削除する", job_path(job.id), method: :delete, data: { confirm: "このお仕事を削除してよろしいですか？" }, id: "Destroy-btn-Show1", onclick: "Destroyjobshow()" , class: "style-jobsshow-destroybtn style-boder-smallradius my-3" %>
            <% elsif job.progress == 1 %>
              <%= link_to "jobs/entry_confirm/#{job.id}" do %>
                <button class="style-jobs-editbtn style-boder-smallradius">エントリー有</button>
              <% end %>
            <% elsif job.progress == 2 %>
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-editbtn style-boder-smallradius">契約手続き中</button>
              <% end %>
            <% elsif job.progress == 3 %>
              <button class="style-jobs-editbtn style-boder-smallradius">契約中</button>
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-editbtn style-boder-smallradius">完了確認</button>
              <% end %>
            <% elsif job.progress >= 4 %>
              <%= link_to job_path(job.id) do %>
                <button class="style-jobs-editbtn style-boder-smallradius">完了済み</button>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-collapse" class="col-lg-3 sidebar style-ma-thigh d-lg-block d-none">
  <ul class="nav style-dblock">
    <li class="style-smunderbar">
      <%= link_to hero_path(current_hero.id), class: "style-mypage-listitem" do %>
        マイページ
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
    <!--実装まで外す-->
    <!--<li class="style-smunderbar">-->
    <!--  <a href="./../heros/show.html" class="style-mypage-listitem">-->
    <!--    お知らせ-->
    <!--    <i class="fas fa-chevron-right style-mypage-navicon"></i>-->
    <!--  </a>-->
    <!--</li>-->
    <!--<li class="style-smunderbar">-->
    <!--  <a href="./../heros/show.html" class="style-mypage-listitem">-->
    <!--    やることリスト-->
    <!--    <i class="fas fa-chevron-right style-mypage-navicon"></i>-->
    <!--  </a>-->
    <!--</li>-->
    <!--<li class="style-smunderbar">-->
    <!--  <a href="./../heros/chat-heros.html" class="style-mypage-listitem">-->
    <!--    チャット画面-->
    <!--    <i class="fas fa-chevron-right style-mypage-navicon"></i>-->
    <!--  </a>-->
    <!--</li>-->
    <li class="style-smunderbar style-lightblueback">
      <%= link_to jobs_index_path(1), class: "style-mypage-listitem" do %>
        応募中ミッション
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
    <li class="style-smunderbar">
      <%= link_to jobs_index_path(2), class: "style-mypage-listitem" do %>
        契約処理待ちミッション
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
    <li class="style-smunderbar">
      <%= link_to jobs_index_path(3), class: "style-mypage-listitem" do %>
        実施中ミッション
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
    <li class="style-smunderbar">
      <%= link_to jobs_index_path(4), class: "style-mypage-listitem" do %>
        完了ミッション
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
    <li class="style-smunderbar">
      <%= link_to jobs_index_path(5), class: "style-mypage-listitem" do %>
        ミッション履歴
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
  </ul>
  <p class="style-text-bold mt-4">設定</p>
  <ul class="nav style-dblock">
    <li class="style-smunderbar">
      <%= link_to edit_hero_registration_path, class: "style-mypage-listitem" do %>
        プロフィール・パスワード変更
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
    <!--実装まで外す-->
    <!--<li class="style-smunderbar">-->
    <!--  <a href="./../heros/registrations/confirmation.html" class="style-mypage-listitem">-->
    <!--    ミッション必要書類提出-->
    <!--    <i class="fas fa-chevron-right style-mypage-navicon"></i>-->
    <!--  </a>-->
    <!--<li class="style-smunderbar">-->
    <!--  <a href="#" class="style-mypage-listitem">-->
    <!--    残高・振込確認-->
    <!--    <i class="fas fa-chevron-right style-mypage-navicon"></i>-->
    <!--  </a>-->
    <!--</li>-->
    <li class="style-smunderbar">
      <%= link_to destroy_hero_session_path, method: :delete, data: { confirm: "ログアウトしてよろしいですか？" }, id: "Destroy-btn-Show1", onclick: "LogoutFormHeros()" , class: "style-mypage-listitem" do %>
        ログアウト
        <i class="fas fa-chevron-right style-mypage-navicon"></i>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/_top_header.html.erb
<!--ログイン前トップページヘッダー-->
<!--CSSのスタイルシートから持ってきているものはクラスにstyle-が入っている 基本的に初めがbootstrapのCSS 位置調整は1番右-->
<header class="style-header">
  <section class="container-fluid">
    <div class="row">
      <nav class="col-12 navbar navbar-expand-lg fixed-top style-nav style-shadow-rightblack" id="mainNav">
        <!--.navbar-brand はブランドを表示します。-->
          <%= link_to root_path, class: "navbar-brand" do %>
            <figure>
              <img class="" src="/assets/Heros-Logo.png" alt="ハロヒロロゴ画像" height="40px" width="134px">
            </figure>
          <% end %>
        <div class="navbar-nav style-midtext style-ma-rauto">
          <div class="d-none d-lg-block">
            <%= link_to  new_nursing_home_registration_path,id:"btnline" do %>
              <button class="style-topoffices-newmenbtn style-boder-smallradius">事業所新規登録</button>
            <% end %>
            <%= link_to  new_nursing_home_session_path do %>
              <button class="style-helper-toploginbtn style-boder-smallradius mr-3">事業所ログイン</button>
            <% end %>
            <%= link_to  heros_rules_path do %>
              <button class="style-helper-topnewmenbtn style-boder-smallradius">ヒーロー新規登録</button>
            <% end %>
            <%= link_to  new_hero_session_path do %>
              <button class="style-helper-toploginbtn style-boder-smallradius">ヒーローログイン</button>
            <% end %>
          </div>
          <div class="d-lg-none d-block">
            <input type="checkbox" id="OpenSidebarMenu">
            <label for="OpenSidebarMenu" class="style-sidebarIcon" id="SidebarMenuLabel">
              メニュー
            </label>
            <div id="SidebarMenu">
              <ul class="style-sidebarMenuInner">
                <li><%= link_to "事業所新規登録", new_nursing_home_registration_path %></li>
                <li><%= link_to "事業所ログイン", new_nursing_home_session_path %></li>
                <li><%= link_to "ヒーロー新規登録", new_hero_registration_path %></li>
                <li><%= link_to "ヒーローログイン", new_hero_session_path %></li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </section>
</header>

app/views/layouts/application.html.erb
<?php
header('X-FRAME-OPTIONS: SAMEORIGIN');
?>

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title><%= page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
      integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk"
      crossorigin="anonymous" />
  <link rel="stylesheet" href="/assets/style.css" />
  <link rel="stylesheet" href="/assets/page/style.css" />
  <link href="assets/application.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://kit.fontawesome.com/de95f90de5.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
</head>

  <body>
    <%= yield %>
  </body>
  <footer class="footer-nav">
    <div class="footer-nav__conmanyname">
      <h2>ハロヒロについて</h2>
      <ul>
        <li><a href="#">会社概要</a></li>
        <li><a href="＃">SDGSに対する取り組み</a></li>
        <li><a href="#">利用規約</a></li>
      </ul>
    </div>
    <div class="footer-nav__sns-btn">
      <div class="sns-btn__contets">
        <a href="#" class="btn-social-circle btn-social-circle-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </div>
      <div class="sns-btn__contets">
        <a href="#" class="btn-social-circle btn-social-circle-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </div>
      <div class="sns-btn__contets">
        <a href="#" class="btn-social-icon-instagram">
          <span class="btn-social-icon-instagram-square"
            ><i class="fab fa-instagram"></i></span
        ></a>
      </div>
    </div>
    <div class="footer-nav__sdgsimg">
      <img src="/assets/Sdgs-Logo.jpeg" alt="SDGSロゴ" />
    </div>
  </footer>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="/assets/header.js"></script>
</html>